redhat/scylla.spec: add python34-setuptools dependency
Commit 00476c39464 switched some scripts to python3, it introduced an
ImportError: No module named 'pkg_resources'.

Signed-off-by: Amos Kong <amos@scylladb.com>
Message-Id: <293c05d9315ec6c9da1f32e8cb3d2fdf8d8d3924.1545272049.git.amos@scylladb.com>
(cherry picked from commit 385d74db01a9a9597a837c19034c251d2477dfe0)
Signed-off-by: Glauber Costa <glauber@scylladb.com>